### ISSUE TITLE
Can't create event

### ISSUE THREAD

**Issue by mschering** [Intermesh/groupoffice-server#10]
When logged in as "henk" *(phpunit db) I get an error when creating a new event:

IFW\Exception\Forbidden: You're (user ID: 2) not permitted to create GO\Modules\GroupOffice\Calendar\Model\RecurrenceRule array (
  'eventId' => 7,
) in /var/www/groupoffice-server/lib/IFW/Orm/Record.php: 1305

**Comment by dehart** [comment]
Solved and added test cases
