### ISSUE TITLE
Adding permission to module

### ISSUE THREAD

**Issue by dehart** [Intermesh/groupoffice-server#3]
Try adding a group to a module

**FAILED SQL**
SELECT t.id, t.name, GROUP_CONCAT(moduleGroups.action) AS actions \nFROM `auth_group` `t`\nINNER JOIN `modules_module_group` `moduleGroups` ON (`t`.`id` = `moduleGroups`.`groupId` AND (\t(\n\t\t`moduleGroups`.`moduleId` = 23\n\t)))\nWHERE\n(\n\t`t`.`deleted` != true\n)\nGROUP BY `t`.`id`\n\n\nORDER BY `t`.`name` ASC",

**STACK TRACE**
SQLSTATE[42000]: Syntax error or access violation: 1055 'go7_2.t.name' isn't in GROUP BY",
        "[171ms][IFW\\ErrorHandler:58] PDOException: SQLSTATE[42000]: Syntax error or access violation: 1055 'go7_2.t.name' isn't in GROUP BY in \/var\/www\/groupoffice-7.0\/groupoffice-server\/lib\/IFW\/Db\/Command.php:223",
        "[171ms][IFW\\ErrorHandler:58] Stack trace:",
        "[171ms][IFW\\ErrorHandler:58] #0 \/var\/www\/groupoffice-7.0\/groupoffice-server\/lib\/IFW\/Db\/Command.php(223): PDOStatement->execute()",
        "[171ms][IFW\\ErrorHandler:58] #1 \/var\/www\/groupoffice-7.0\/groupoffice-server\/lib\/IFW\/Orm\/Store.php(45): IFW\\Db\\Command->execute()",
        "[171ms][IFW\\ErrorHandler:58] #2 \/var\/www\/groupoffice-7.0\/groupoffice-server\/lib\/IFW\/Data\/Store.php(158): IFW\\Orm\\Store->getIterator()",
        "[171ms][IFW\\ErrorHandler:58] #3 \/var\/www\/groupoffice-7.0\/groupoffice-server\/GO\/Core\/Controller.php(102): IFW\\Data\\Store->toArray()",
        "[171ms][IFW\\ErrorHandler:58] #4 \/var\/www\/groupoffice-7.0\/groupoffice-server\/GO\/Core\/Modules\/Controller\/PermissionsController.php(71): GO\\Core\\Controller->renderStore(Object(IFW\\Data\\Store))",
        "[171ms][IFW\\ErrorHandler:58] #5 [internal function]: GO\\Core\\Modules\\Controller\\PermissionsController->actionStore('GO\\\\Modules\\\\Grou...', '')",
        "[171ms][IFW\\ErrorHandler:58] #6 \/var\/www\/groupoffice-7.0\/groupoffice-server\/lib\/IFW\/Controller.php(161): call_user_func_array(Array, Array)",
        "[171ms][IFW\\ErrorHandler:58] #7 \/var\/www\/groupoffice-7.0\/groupoffice-server\/GO\/Core\/Controller.php(113): IFW\\Controller->callMethodWithParams('actionstore', Array)",
        "[172ms][IFW\\ErrorHandler:58] #8 \/var\/www\/groupoffice-7.0\/groupoffice-server\/lib\/IFW\/Controller.php(129): GO\\Core\\Controller->callMethodWithParams('actionstore', Array)",

**Comment by dehart** [comment]
I've change PermissionsController.php:27 to the following to solve:
						->groupBy(['t.id','t.name'])

**Comment by mschering** [comment]
Looks like the right solution
